train:
  seat_count: 100
  sections:
    - A
    - B
  routes:
    - from: London
      to: France
      price: 20
    - from: Paris
      to: Berlin
      price: 30
    - from: New York
      to: Los Angeles
      price: 40
auth:
  secret_key: VhkgDGkS-k0J9A2KTZJm31kZnvQon7viSD2OtkB4V_c=
  expire: 3600
roles:
  - email: admin@test.com
    caps:
      - admin
      - read
      - write
  - email: read@test.com
    caps:
      - read
  - email: write@test.com
    caps:
      - write